#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build:
    working_directory: ~/opt-out
    docker:
      - image: circleci/node@sha256:5870e9c11af4bf5f0cf74034df01040ec4c2bcb5b6369c67ee4eece73a8eb3a7

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ./node_modules
            - ./.next/cache
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
