#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  build:
    working_directory: ~/yourdigitalrights
    docker:
      - image: cimg/node:18.17.0-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - browser-tools/install-chrome:
          replace-existing: true 

      - run: npm install --legacy-peer-deps

      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./src/.next/cache
            - ./.next/cache

      # run tests!
      - run: npm test
